### ISSUE TITLE
Import from SDF format

### ISSUE THREAD

**Issue by jotsetung** [EuracBiomedicalResearch/CompoundDb#1]
Create functions to import compound information from files in SDF format. This should work on files from HMDB, ChEBI and LipidMaps.

**Comment by stanstrup** [comment]
I have a pubchem method ready I can push soonish.

**Comment by jotsetung** [comment]
While implementing the *generic* SDF import function I realized that LipidMaps does not provide always a compound name. @stanstrup, your approach was to combine the columns `COMMON_NAME`, `SYSTEMATIC_NAME` and `SYNONYMS` into this field. I was rather thinking whether we should add a second table in the database that links individual aliases and synonyms to the original id and, for LipidMaps, just report the `COMMON_NAME` in the `compound_name` field.

**Comment by stanstrup** [comment]
But do all have a COMMON_NAME? My thought was that that might have been missing. But I don't remember if I ever checked if that was the case.
If that is always available then yes it is fine to just use that one for the main table.

**Comment by jotsetung** [comment]
Nope, not all have a `COMMON_NAME` that's the issue. I'm checking now `SYSTEMATIC_NAME`.

**Comment by jotsetung** [comment]
nope, for the 40,000 entries ~ 10,000 have a missing `COMMON_NAME` and ~ 5,000 a missing `SYSTEMATIC_NAME`. What if we use by default the `SYSTEMATIC_NAME` and for those missing use the `COMMON_NAME`?  Or other way round? I don't know which of the two is more commonly used...

**Comment by stanstrup** [comment]
You could do: If there is `COMMON_NAME` use that. Otherwise `SYNONYMS` otherwise `SYSTEMATIC_NAME`. I was just too lazy for that in the first frenzy.

And then link all in a separate table if you want. That would allow the browser to show just one sensible name and I could add a button to show all known synonyms. It would be nice to be able to create a union of different dbs with no inchi overlap but possible names merged.

**Comment by stanstrup** [comment]
I would much rather have common name default. When you work with your data that is much much easier to understand what you are looking at.

**Comment by jotsetung** [comment]
OK, then it will be as you suggest.

**Comment by stanstrup** [comment]
How do you plan to handle something like pubchem that is multiple SDFs?
In my method I do an sqlite for each SDF file (multithreaded) and then append to one large sqlite in the end to keep the memory use as sane as possible.

Any thoughts on that?

```r
library(R.utils)
library(ChemmineR)
library(dplyr)
library(tidyr)
library(parallel)
library(pbapply)

# rds: 6.4 GB
# to generate ~60GB
# in memory after: 53.5GB
# sqlite: 43GB

generate_pubchem_tbl_single <- function(sdf.gz_path, tmpdir){
require(R.utils)
require(ChemmineR)
require(dplyr)
require(dbplyr)
require(RSQLite)

print(paste0(sdf.gz_path,"\n"))
    
sqlite_path <- paste0(tmpdir,"/",basename(sub('.sdf.gz','.sqlite',sdf.gz_path)))

if(file.exists(sqlite_path)){ # if we crashed before simply skip
    return(sqlite_path)
}

# unpack and read
gunzip(sdf.gz_path, remove = FALSE, skip = TRUE)
SDF <- read.SDFset(sub('.sdf.gz','.sdf',sdf.gz_path))
unlink(sub('.sdf.gz','.sdf',sdf.gz_path))

# fix file
valid <- validSDF(SDF)
SDF <- SDF[valid]

SDF_tbl <- datablock2ma(datablock(SDF))

pubchem_tbl <- SDF_tbl %>%
                     as_data_frame %>%
                     rowwise %>% 
                     mutate(name = paste(unique(c(PUBCHEM_IUPAC_TRADITIONAL_NAME, PUBCHEM_IUPAC_NAME, PUBCHEM_IUPAC_SYSTEMATIC_NAME, PUBCHEM_IUPAC_CAS_NAME)), collapse="; ")) %>%
                     ungroup %>% 
                     select(id = PUBCHEM_COMPOUND_CID, name, inchi = PUBCHEM_IUPAC_INCHI, formula = PUBCHEM_MOLECULAR_FORMULA, mass = PUBCHEM_EXACT_MASS) %>%
                     mutate(id = paste0("CID",id))



pubchem_db <- src_sqlite(path=sqlite_path, create = TRUE)
db_insert_into(pubchem_db$con, table="pubchem_tbl", values=pubchem_tbl) 
rm(pubchem_db)
gc()


return(sqlite_path)


}
```



```r
generate_pubchem_tbl <- function(files, ncores = parallel::detectCores()){
require(RSQLite)
        
    if(ncores>1){
        cl=makeCluster(ncores, outfile="outpar.txt")
        clusterExport(cl,'generate_pubchem_tbl_single')
        pboptions(use_lb=TRUE)
        pubchem_sql_paths <- pbsapply(files, generate_pubchem_tbl_single, tmpdir=tempdir(), cl = cl)
        stopCluster(cl)
    }else{
        pubchem_sql_paths <- sapply(files, generate_pubchem_tbl_single, tmpdir=tempdir())
    }
    
    
    sqlite_combined_path <- tempfile(fileext = ".sqlite")
    pubchem_db <- src_sqlite(path=sqlite_combined_path, create = TRUE)
    
    for(i in seq_along(pubchem_sql_paths)){
        pubchem_single_db <- src_sqlite(path=pubchem_sql_paths[i], create = FALSE)
        db_insert_into(pubchem_db$con, table="pubchem_tbl", values=tbl(pubchem_single_db$con, "pubchem_tbl") %>% collect()) 
        rm(pubchem_single_db)
        gc()
        unlink(pubchem_sql_paths[i])
    }
    

    pubchem_all <- tbl(pubchem_db$con, "pubchem_tbl") %>% collect()
    rm(pubchem_db)
    gc()
    unlink(sqlite_combined_path)
    
    return(pubchem_all)
}
```


```r
files <- list.files("D:/data/JanS/Databases/PubChem/SDF/",pattern = ".sdf.gz", full.names = TRUE)
pubchem_tbl <- generate_pubchem_tbl(files, detectCores())
```

**Comment by jotsetung** [comment]
For starters I would just implement a function that can read a single PubChem SDF file (see if e.g. https://github.com/EuracBiomedicalResearch/CompoundDb/blob/master/R/createCompDbPackage.R#L90:L116 could be adapted to be used on PubChem). 

We could then implement/adapt the `compound_tbl_sdf` function (I renamed the `generate_...` to that to keep it shorter, also, this `_tbl_sdf` function can read already SDF files from HMDB, LipidMaps and ChEBI) to process multiple files. You think memory demand is too large to process all PubChem files into one single `tbl`?

Note that I removed some of the `dplyr` stuff too to reduce the number of imports from other packages.
Also, I thought we keep this `compound_tbl_sdf` functions that can be used in the same fashion than your `generate_` functions, i.e. don't create a database but simply return a `tbl`.
In addition, I would implement the functionality to create `CompDb` databases from input files along with functions to access the `CompDb` databases to get the `tbl` in the correct format from them.

**Comment by stanstrup** [comment]
The memory demand is around 60GB for the complete tbl plus 1GB for each core you want to use doing generation. With 32 cores the processing time was about 15 hours. Doing it single threaded I think will take more than a week if not several.

So even doing as I did, reading everything into memory to return a tbl, is out of the question for most people in this case.

**Comment by stanstrup** [comment]
Re names:
What about allowing `_colmap` to be several columns so that you can `rbind` what is in several columns to the synonyms table?
Then you could generically take the first synonym from synonyms if name is empty.

**Comment by jotsetung** [comment]
Re memory demand: impressive; well, then a function that processes one file at a time and returns a `tbl` seems best to me. One could then implement a wrapper to save the stuff into a database after importing, deleting the `tbl` and return. I would then however write everything into a single database - and I'm not sure if SQLite is good enough in handling such large data (save to MySQL?).

**Comment by jotsetung** [comment]
Re names: I don't quite understand. Presently I'm just putting the synonyms as a list into the resulting `tbl`. That way I can separate the information cleanly before saving to the `compound` and `synonym` database tables.

**Comment by stanstrup** [comment]
Re memory demand: I can probably make the whole sqlite available somehow if you want to play with it.


Re names: 

My thought was that instead of having

```r
c(id = "PUBCHEM_COMPOUND_CID",
                       name = "PUBCHEM_IUPAC_TRADITIONAL_NAME",
                       inchi = "PUBCHEM_IUPAC_INCHI",
                       formula = "PUBCHEM_MOLECULAR_FORMULA",
                       mass = "PUBCHEM_EXACT_MASS",
                       synonyms = "PUBCHEM_IUPAC_TRADITIONAL_NAME" 
                       )
```

It would be nice to be able to say:

```r
list(id = "PUBCHEM_COMPOUND_CID",
     name = "PUBCHEM_IUPAC_TRADITIONAL_NAME",
     inchi = "PUBCHEM_IUPAC_INCHI",
     formula = "PUBCHEM_MOLECULAR_FORMULA",
     mass = "PUBCHEM_EXACT_MASS",
     synonyms = c("PUBCHEM_IUPAC_TRADITIONAL_NAME", "PUBCHEM_IUPAC_SYSTEMATIC_NAME", "PUBCHEM_IUPAC_CAS_NAME", "PUBCHEM_IUPAC_OPENEYE_NAME", "PUBCHEM_IUPAC_NAME")
     )
```

And have all the "name columns" in synonym "rbound" in the synonyms table you have (+make unique).
It is helpful having as many names as possible.

Then a database merge method that matches and inchis and merges unique synonyms from the different DBs would be cool.

**Comment by jotsetung** [comment]
Makes sense. But I wouldn't re-list the `..TRADITIONAL_NAME` in the `synonyms` if it was already used as a `name`.

Wow, a database merge method. Sounds interesting - and tricky. For that we need to define use cases.

I am wondering whether we wouldn't have to define a `MultiSourceCmpDb` class/database then to track also from which source the compound comes... I would say that's a second step.

**Comment by stanstrup** [comment]
Right. No need to duplicate.

The use case for the merge would again be the annotation. But I suppose that can be handled there as well.

**Comment by jotsetung** [comment]
Opened an issue #11 related to the database merge.
