### ISSUE TITLE
Compound spectra

### ISSUE THREAD

**Issue by stanstrup** [EuracBiomedicalResearch/CompoundDb#17]
Maybe consider if it could be reasonable to hold spectra somehow (as available through MoNA for example).

**Comment by jotsetung** [comment]
Yes, that's something we should include. The database layout helps there, because we can then *just* add an additional *spectrum* table and don't have to change the other tables.

**Comment by jotsetung** [comment]
YESSSSS, we need to include the spectra...

**Comment by jotsetung** [comment]
closing this issue keeping discussion on in issue #22
