### ISSUE TITLE
object and x same in man page?

### ISSUE THREAD

**Issue by stanstrup** [EuracBiomedicalResearch/CompoundDb#18]
Aren't x and object the same kind of thing? 
Should they be named the same across functions?

https://github.com/EuracBiomedicalResearch/CompoundDb/blob/389c16c6234b68308a9a18630110f450f1dc4245/man/CompDb.Rd#L46

https://github.com/EuracBiomedicalResearch/CompoundDb/blob/389c16c6234b68308a9a18630110f450f1dc4245/man/CompDb.Rd#L31-L33

**Comment by jotsetung** [comment]
Yes they are. Problem is:
```r
> methods::show
standardGeneric for "show" defined from package "methods"

function (object) 
standardGeneric("show")
<bytecode: 0x7fe3ab627800>
<environment: 0x7fe3ab91a608>
Methods may be defined for arguments: object
Use  showMethods("show")  for currently available ones.
(This generic function excludes non-simple inheritance; see ?setIs)

```

and 
```r
> BiocGenerics::dbconn
standardGeneric for "dbconn" defined from package "BiocGenerics"

function (x) 
standardGeneric("dbconn")
<environment: 0x7fe3a9763648>
Methods may be defined for arguments: x
Use  showMethods("dbconn")  for currently available ones.
```
so, in one method the first parameter is called `object` and in the other `x`. It's annoying but there is no way around that.

**Comment by jotsetung** [comment]
Or, you can change that, but then you'll get a `WARNING` each time you build, check or install the package.

**Comment by stanstrup** [comment]
Ah I see.
