### ISSUE TITLE
make createCompDbPackage return package path

### ISSUE THREAD

**Issue by stanstrup** [EuracBiomedicalResearch/CompoundDb#19]
Wouldn't it make sense if `createCompDbPackage` returned the path of the package?

Then you could grab that and install directly.

https://github.com/EuracBiomedicalResearch/CompoundDb/blob/690258d9b7aca0439f6f8658507deffdeffbed93/R/createCompDbPackage.R#L614

**Comment by jotsetung** [comment]
makes sense. Thanks!

**Comment by stanstrup** [comment]
Fantastic!
