### ISSUE TITLE
Add functionality to convert mass to m/z and vice versa

### ISSUE THREAD

**Issue by jotsetung** [EuracBiomedicalResearch/CompoundDb#38]
Add functionality to convert mass to m/z and back given adduct definitions such as `"[M+H]+"`. This needs:
- definition of adducts and related conversions/mass differences.
- function to map from mass to m/z: `mass2mz`
- function to map from m/z to mass: `mz2mass`

The input for the function should be a `numeric` with masses respectively m/z values. The output a `list` of length equal to the input vector. Each element should be a named `numeric` of length equal to the number of specified adducts, names being the adduct name and values the converted value.

**Comment by jotsetung** [comment]
Eventually we should add an optional `ifNotFound` parameter to choose what to do if the adduct definition was not found with options `NA`, "error".

**Comment by stanstrup** [comment]
Maybe these are useful: https://github.com/stanstrup/commonMZ/tree/master/inst/extdata

I don't remember if the inchi is in there but if so you can also check if the compound is in neutral state. For example Anthocyanins have a persistent charge. If you don't account for that you will get the wrong m/z.

**Comment by jotsetung** [comment]
Awesome! Nice ressource indeed! I did take the definitions from the camera rules. I'll also check the other files. Once the code is in place I'd really appreciate if you look through to see if all is correct.

**Comment by stanstrup** [comment]
Great.
Would it not make sense to take the data directly from the commonMZ package? There are function to get the data so you don't need to read the excel file on your side. It is a dedicated package now.

**Comment by jotsetung** [comment]
That would make sense indeed. I would just need a `data.frame` with the content of the xls files - what functions would I need to get these?

Other question: is it needed to have these files as *xls* files? If they were tab delimited text files I could simply load them with `read.table` ... and we could reduce the number of dependencies.

**Comment by stanstrup** [comment]
The function you need is MZ_CAMERA. A tibble is returned. I understand the desire the keep dependencies limited. I kept it this way just because it is easier to work with. The adducts are color coded by type so you can easier get an overview when actually working with the table. Also you avoid that if people add things to the table excel has a nasty desire to change the delimiter in csv files (based on the machine locale).

**Comment by jotsetung** [comment]
Thanks! I'm now importing the definitions directly from your `commonMZ` package with the `MZ_CAMERA` function 👍

**Comment by stanstrup** [comment]
Btw. I saw that you add instructions to install dependencies. Those should work automatically when you install the package I assume.
Even github packages can be automatically handled with devtools if you define them as remote in the description file. e.g. `Remotes: stanstrup/commonMZ`

**Comment by jotsetung** [comment]
Thanks @stanstrup! I knew there was something like that, but couldn't remember. I've added `commonMZ` now as a remote.

**Comment by jotsetung** [comment]
BTW, just to be on the safe side: @stanstrup can you just check that I'm converting correctly?

To calculate masses from m/z (`adduct` below is the *adduct* `data.frame` from `commonMZ`:

```r
mass <- (adduct$nmol * mz + adduct$massdiff) / adduct$charge
```

and other way round:

```r
mzr <- (adduct$charge * mass - adduct$massdiff) / adduct$nmol
```

I cross-checked with some compounds/adducts in HMDB, but it's never bad to have a second look at it.

**Comment by stanstrup** [comment]
Don't you have mz/mass exchanged? I assume by mass you mean the neutral mass.

**Comment by jotsetung** [comment]
yes, `mass` is the neutral (monoisotopic) mass.

Could be that I mixed it up - am quite confused at present. How would you then calculate the adduct m/z if you have the mass and *vice versa*?

**Comment by jotsetung** [comment]
Aaaah! Yes! You're right! I used `res` and `z` as variable names and got mislead by the `R` function names! It should be:

mass -> m/z
```r
mz <- (adduct$nmol * mass + adduct$massdiff) / adduct$charge
```

m/z -> mass
```r
mass <- (adduct$charge * mz - adduct$massdiff) / adduct$nmol
```

**Comment by stanstrup** [comment]
Yes now I have the same as you :-)
