### ISSUE TITLE
Doc lists wrong required columns

### ISSUE THREAD

**Issue by stanstrup** [EuracBiomedicalResearch/CompoundDb#45]
Should be `compound_id` and `compound_name`. `inchi_key` is also required but not mentioned in this place in the doc.

https://github.com/EuracBiomedicalResearch/CompoundDb/blob/23d7958037dd63867dfe3a8f9be2a5eaf5bc98de/R/createCompDbPackage.R#L361

**Comment by jorainer** [comment]
could you eventually make a pull request fixing this?

**Comment by stanstrup** [comment]
Shall do.

**Comment by stanstrup** [comment]
PR: https://github.com/EuracBiomedicalResearch/CompoundDb/pull/48

It is unclear if the doc should also be changed for lipidblast. But I assume it is done the same way.
