### ISSUE TITLE
Setting write permission in CompDb

### ISSUE THREAD

**Issue by stanstrup** [EuracBiomedicalResearch/CompoundDb#47]
It would be nice to be able to set the `RSQLite::SQLITE_RW` flag for the database connection.

https://github.com/EuracBiomedicalResearch/CompoundDb/blob/c6358539c90adc48eb9ba639a7c3f432390046b0/R/CompDb.R#L201

That way more advanced direct hacking is easier so you don't have to make a new connection "manually".

**Comment by jorainer** [comment]
Feel free to make a pull request on that. Ideally, add a parameter `flags` to the `CompDb` constructor that is passed along to the connection.

**Comment by stanstrup** [comment]
PR: https://github.com/EuracBiomedicalResearch/CompoundDb/pull/49
