### ISSUE TITLE
extract cmpDb spectra considering spectrum_id

### ISSUE THREAD

**Issue by jmbadia** [EuracBiomedicalResearch/CompoundDb#64]
Hi Johannes,
As you know, I am trying to fit my BD and MS2 workflow identification to your amazing tools. 
In one of the steps, we look on a CompDb object for spectra that match specific requirements (polarity, mass, originaldb, ...), and then we need to extract such spectra in order to compare them with our query spectrum. i.e. it is necessary to extract spectra from a compDb object considering their 'spectrum_id' value. Something similar to 

spectraSbstd <- Spectra(CompDb..100KMS2ID.1.0, filter = ~ spectrum_id %in% c(100002, 25, 68)

spectrum_id is not considered as a variable in any filter supported by CompDb. How can I adress this need? Do I need to extend a new filter from AnnotationFilter::AnnotationFilter class?

Thanks for all your support

**Comment by jorainer** [comment]
Exactly - you would need a `SpectrumIdFilter` class extending the `AnnotationFilter` virtual class. I will add that quickly.

**Comment by jorainer** [comment]
The `SpectrumIdFilter` (allowing you to filter using e.g. `filter = ~ spectrum_id %in% c(1000002, 43, 56)`) is implemented in the most recent version (0.6.1).

**Comment by jmbadia** [comment]
wow. Thanks @jorainer !

**Comment by jorainer** [comment]
no prob - let me know if you need anything else
