### ISSUE TITLE
loading invalid sdf  

### ISSUE THREAD

**Issue by jmbadia** [EuracBiomedicalResearch/CompoundDb#69]
Hi, 
I parsed [negative LC-MS/MS spectra from MoNA](https://mona.fiehnlab.ucdavis.edu/spectra/browse?query=tags.text==%22LC-MS%22%20and%20metaData=q=%27name==%22ms%20level%22%20and%20value==%22MS2%22%27%20and%20metaData=q=%27name==%22ionization%20mode%22%20and%20value==%22negative%22%27) by using the `compound_tbl_sdf(sdf file) `function. It returns the following warning;
```
In read.SDFset(file) :
    54 invalid SDFs detected. To fix, run: valid <- validSDF(sdfset); sdfset <- sdfset[valid]
```
resulting in a result with invalid SDF we know nothing about
Maybe we could offer an argument ( `compound_tbl_sdf(..., onlyValid) `)  in order not to load such invalid SDFs by applying the code suggested by the warning.

**Comment by jmbadia** [comment]
Thanks @jorainer . Looks great to me.

**Comment by jorainer** [comment]
I'm closing the issue now - feel free to re-open if it's not working.
