### ISSUE TITLE
support gz compressed sdf files

### ISSUE THREAD

**Issue by stanstrup** [EuracBiomedicalResearch/CompoundDb#7]
For Pubchem. assume same name as gz file.

```r
gunzip(file, remove = FALSE, skip = TRUE)
SDF <- read.SDFset(sub('.sdf.gz','.sdf',file))
unlink(sub('.sdf.gz','.sdf',file))
```

**Comment by jotsetung** [comment]
`read.SDFset` has built-in support for gzipped files, so no need to unzip them prior to reading.

**Comment by stanstrup** [comment]
Wow. I wonder how you found that. Seems undocumented.
It looks like it is a bonus feature from using `readLines` that apparently automatically detects a gz file and opens the content.
