### ISSUE TITLE
Implement a StandardsDb that extends CompoundDb

### ISSUE THREAD

**Issue by jorainer** [EuracBiomedicalResearch/CompoundDb#77]
Add a `StandardsDb` object/database layout that extends the `CompDb` by adding an `ion` table which contains retention times and adducts of lab-standards (for a certain setup or matrix).

an `adducts` (or `ions`) method would then return this information, joining the `ion` table with the `compound` table.

**Comment by jorainer** [comment]
`StandardsDb` (or `IonDb`?) should extend `CompDb`. Things to implement would be:

- [ ] validation method of `IonDb` should check for presence and correct format of the `ms_ion` database table.
- [ ] `insertIon` method. `insertIon,CompDb`: create the `ms_ion` table and insert the information. `insertIon,IonDb` adds additional ion(s) to the `ms_ion` table. 
- [ ] `ions` function to retrieve a `data.frame` with all (or selected) entries from the `ion` table.

**Comment by jorainer** [comment]
Proposed workflow to create/add info to an `IonDb` would be:

1) create a `CompDb` e.g. from HMDB.
2) add ions measured on a certain LC-MS setup to that converting it from `CompDb` to `IonDb`.
3) support adding additional ion information later to the same `IonDb`.
4) support adding MS/MS spectra to the `IonDb` **and link them to the ion**.

Some properties:
- `CompDb` databases are read-only
- `IonDb` databases should support writing data to it.
- there should be a separate `IonDb` for different LC-MS setups or sample sources (since rt and/or adducts and/or MS/MS spectra could be different).

**Comment by jorainer** [comment]
Most of it is implemented. What remains is how to add MS/MS spectra and how to link them to the ion - and/or the compound?

@andreavicini , can you maybe also start thinking how to best solve that? Spectra in the `msms_spectra` are linked to the `ms_compounds` table via the `compound_id` - and we have also ions linked to compounds with the same ID. But for a direct link between ions and spectra we might need an additional table mapping ion IDs to spectrum IDs...

**Comment by andreavicini** [comment]
I realized that I’m not sure I completely understood so I wanted to ask a few clarifications. Should we implement the possibility to add more MS/MS spectra in addition to those that are added when creating a `ionDb`?
Why do we want to create a direct link between ions and spectra without indirectly passing from `compound_id`? Is that because only certain adducts of a given compound have to be linked to a given spectrum? In that case the additional table has to be provided by the user, right?

**Comment by jorainer** [comment]
You're right. Maybe that makes it all just too complicated and in the end unusable. Let's just add the possibility to add MS/MS spectra and link them to `compound_id`. Then this functionality would be even better to have just for `CompDb` (`IonDb` would anyway inherit it then). The definition of the method would then be:

```r
setMethod("insertSpectra", signature(object = "CompDb", spectra = "Spectra"), function(object, spectra, ...) {
})
```

**Comment by andreavicini** [comment]
I've just rembered, since a `CompDb` is read only would it still work to have the `insertSpectra` defined for it and not only for `ionDb`?

**Comment by andreavicini** [comment]
Thank you! I noticed that a example database in the package has both fields `collision_energy` (but it contains only NA) and `collision_energy_text`. Why do we have these two different fields? Lastly, should I require that the input spectra has the variable `"compound_id"`, right?
