### ISSUE TITLE
insertIon method

### ISSUE THREAD

**Issue by jorainer** [EuracBiomedicalResearch/CompoundDb#79]
`insertIon` is supposed to add information to the `ms_ion` table of an `IonDb` object. The current workflow would be:

1) create or use an existing `CompDb`.
2) Call `insertIon` on that `CompDb` to convert the database to an `IonDb` (i.e. create the `ms_ion` table) and insert the ion information. If the object is already an `IonDb` (or has a `ms_ion` table) add the data to the existing `ms_ion` table.

Propsed signature:

```r
setMethod("insertIon", "CompDb", function(object, ions, dbcon = dbconn(object)))
``` 

- call `.validCompDb` on `dbconn`, if `FALSE`: copy tables from `dbconn(object)` to `dbcon`.
- check that the `data.frame` provided with `ions` is in the right format and contains the expected information:
  - has a column `"compound_id"` and all entries in `"compound_id"` are present in the `"compound_id"` column of the `ms_compound` table of `object`.
  - has columns `"adduct"` (of type `character`), `"mz"` (of type `numeric`) and `"rt"` (of type `numeric`).
- create a new `ms_ion` table if it does not exist: add an additional column `"ms_ion_id"` with the primary key (integer) of the rows.

**Comment by jorainer** [comment]
I try to explain the expected workflow: the user is supposed to have created (or downloaded) first a `CompDb` with compound annotations from e.g. HMDB. The goal would be to add also ion information to that database an hence convert the database to a `IonDb`.

One possible workflow would be, given that `cdb` is an existing `CompDb` and `ions` is a `data.frame` with ion information the user wants to add:

```r
## create a new SQLite database that will contain the IonDb
idbcon <- dbConnect(SQLite(), "my_ion_db.sqlite")
## add ions to the database:
idb <- insertIons(cdb, ions, dbcon = idbcon)
## What this call needs to do:
## - copy all content from the original `cdb` to the new database
## - create the ms_ion table and add the ions to that
## - return an IonDb object
```

If the user wants to add additional ions it would be much easier, because he/she has already an `IonDb`:

```r
## no need here to specify a different database or copy content, because `idb` does already have
## the required table and is expected to be read-write
idb <- insertIons(idb, ions)
```

I agree that this workflow is not that intuitive - because we're changing from a `CompDb` to a `IonDb` with the `insertIons` call. Maybe we should think of an alternative @andreavicini ?

**Comment by jorainer** [comment]
What about: `insertIons` is **only** defined for `IonDb` objects? The user would need to create first a `IonDb` database/object with the `IonDb` constructor function:

```r
icon <- dbConnect(SQLite(), "my_ion_db.sqlite")
idb <- IonDb(dbcon = icon, CompDb = cdb)
```

A call like the one above is supposed to copy all tables from the `CompDb` over to `dbcon` and create in addition the `ms_ion` table and return the `IonDb` object with the connection to the new database (`dbcon`). If `CompDb` is missing the specified database connection is supposed to be for a database containing already the tables needed for an `IonDb`.

From here on `insertIons` could be called to insert ions in the new database.

Would that be a better workflow? @andreavicini what do you think?

**Comment by andreavicini** [comment]
I like this second approach and maybe it's a bit clearer. I'm not sure if I understood what you mean in the case `CompDb` is missing. Should it have like empty tables for each of the required tables?

**Comment by jorainer** [comment]
What I meant with `CompDb` is missing is the following: 

```r
idb <- IonDb(dbcon = icon, CompDb = cdb)
```

is supposed to create a **new** IonDb database from content taken from the CompDb `cdb`. We should however also allow a call like:

```r
idb <- IonDb(dbcin = icon)
```

in which case `icon` is expected to be the database connection to an already existing IonDb (with all the required tables). This call should allow users to load a previously created database.

So, the `IonDb` function should be something like:

```r
IonDb <- function(dbcon, CompDb) {
    if (!missing(CompDb)) {
        ## Call a function that copies the content from CompDb over to dbcon
        ## and create the other required tables for IonDb in dbcon
    }
    ## assign dbcon to @dbcon, check validity of the database and return it
}
```
