### ISSUE TITLE
non integer msLevel values

### ISSUE THREAD

**Issue by jmbadia** [EuracBiomedicalResearch/CompoundDb#80]
In MoNA [I have found some spectra](https://www.metabolomicsworkbench.org/databases/refmet/massbank.php?SORT=ms_level&EXACTNAME=Kynurenine&REGNO=) with non-orthodox msLevel entries, such as "MS2 to MS5 composite".
Maybe it would be a good idea not to use integers for _msLevel_ but factors?

**Comment by jorainer** [comment]
Hm, I'm not sure I want to change the whole layout (given that this will also have implications on `Spectra` and other packages that depend on that) based on some special cases. I would then maybe rather want to have an `NA_integer_` MS level for these, but have an additional column `ms_level_text` that contains the original information from MoNA? Note that adding additional columns to a `CompDb` is never a problem, just changing/removing the "minimally required" ones would be problematic.

**Comment by jmbadia** [comment]
I have seen that you usually link the commit to the issue, @jorainer. I'll copy that next time. Now I guess I can link the issue to the pull request #81.

**Comment by jorainer** [comment]
Closing this issue now as it seems to be *fixed* by PR #72 . Feel free to re-open if needed.
